blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Ask for Help
    url: https://github.com/ReactSphere/reactsphere-first-contribution/discussions
    about: Ask questions or get help with contributing.
